
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: callhomeconfigs.core.arlon.io
spec:
  group: core.arlon.io
  names:
    kind: CallHomeConfig
    listKind: CallHomeConfigList
    plural: callhomeconfigs
    singular: callhomeconfig
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: CallHomeConfig is the Schema for the callhomeconfigs API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: CallHomeConfigSpec defines the desired state of CallHomeConfig.
              The resource's status becomes 'complete' when a target secret named
              TargetSecretName is successfully created in the TargetNamespace of the
              workload cluster identified by ManagementClusterUrl and authenticated
              via the kubeconfig contained in the secret named KubeconfigSecretName
              in the management cluster. The target secret will contain a kubeconfig
              generated from the token associated with the service account named ServiceAccountName
              in the management cluster.
            properties:
              kubeconfigSecretKeyName:
                description: Name of key inside of the secret that holds the kubeconfig
                type: string
              kubeconfigSecretName:
                description: Name of secret containing kubeconfig for workload cluster
                type: string
              managementClusterUrl:
                description: The URL of the management cluster
                type: string
              serviceAccountName:
                description: Name of autoscaler service account name in the management
                  cluster
                type: string
              targetNamespace:
                description: Name of namespace inside workload cluster in which to
                  create new kubeconfig secret
                type: string
              targetSecretKeyName:
                description: Name of key holding the kubeconfig inside of the target
                  secret
                type: string
              targetSecretName:
                description: Name of secret inside workload cluster
                type: string
            required:
            - kubeconfigSecretKeyName
            - kubeconfigSecretName
            - managementClusterUrl
            - serviceAccountName
            - targetNamespace
            - targetSecretKeyName
            - targetSecretName
            type: object
          status:
            description: CallHomeConfigStatus defines the observed state of CallHomeConfig
            properties:
              message:
                type: string
              state:
                type: string
            required:
            - message
            - state
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
